---
- name: Configure remote access to PostgreSQL "postgresql.conf"
  template:
    src: centos_postgresql.conf.j2
    dest: "{{ destin_folder_centos_postgresql }}"

- name: Configure remote access to PostgreSQL 
  template:
    src: centos_pg_hba.conf.j2
    dest: "{{ destin_folder_centos_pg_nba }}"
  notify: 
    - Restarted PostgreSQL