---
- name: Configure remote access to PostgreSQL "postgresql.conf"
  template:
    src: debian_postgresql.conf.j2
    dest: "{{ destin_folder_debian_postgresql }}"

- name: Configure remote access to PostgreSQL 
  template:
    src: debian_pg_hba.conf.j2
    dest: "{{ destin_folder_debian_pg_nba }}"
  notify: 
    - Restarted PostgreSQL