---
- name: Install PostgreSQL Server on CentOS
  include_tasks: centos_install_postgresql.yaml
  when:
    - ansible_os_family == "RedHat"

- name: Install PostgreSQL Server on Debian
  include_tasks: debian_install_postgresql.yaml
  when:
    - ansible_os_family == "Debian"